export type {
  BrainLocale,
  TravelIntent,
  BrainMemorySlot,
  CabinClass,
  TravelDates,
  BudgetSlot,
  TravelerSlot,
  ConversationMemory,
  TravelGoals,
  TripPreferences,
  ConversationHistoryTurn,
  ConversationHistory,
  ConversationContext,
  BrainAction,
  SearchRequestHint,
  BookingRequestHint,
  RecommendationHint,
  UiHints,
  BrainResponsePlan,
  IntentClassification,
  ExtractedRequirements,
  BrainTurnInput,
  BrainTurnResult,
  TravelPlan,
  TravelPlanDomainLink,
  TravelPlanPassengerLink,
  TravelDomainBridge,
  TravelSearchDraft,
} from './types'

export {
  ConversationMemoryApi,
  createEmptyMemory,
  emptyBudget,
  emptyTravelDates,
  emptyTravelers,
} from './conversationMemory'

export { ConversationHistoryApi, createEmptyHistory } from './conversationHistory'
export { TravelGoalsApi, createEmptyTravelGoals } from './travelGoals'
export { TripPreferencesApi, createEmptyTripPreferences } from './tripPreferences'
export { ConversationContextApi, createConversationContext } from './conversationContext'
export { IntentClassifier } from './intentClassifier'
export { RequirementExtractor } from './requirementExtractor'
export {
  MissingInformationDetector,
  nextFieldToAsk,
  BRAIN_INTAKE_ORDER,
  isMemorySlotFilled,
} from './missingInformationDetector'
export { TravelPlanner } from './travelPlanner'
export { ResponsePlanner } from './responsePlanner'
export { ContextManager } from './contextManager'
export { MemoryManager } from './memoryManager'
export { ConversationOrchestrator } from './conversationOrchestrator'
export type { ConversationOrchestratorHandle, ConversationOrchestratorOptions } from './conversationOrchestrator'
export { buildContextualFollowUp, promptForField } from './contextualReply'
export { buildTravelPlan } from './travelPlanBuilder'
export { buildTravelDomainBridge } from './domainBridge'

export {
  resetBrainIntegrationSessions,
  isBrainConciergeIntegrationEnabled,
  isBrainAgentHandoffEnabled,
  isBrainVoiceIntegrationEnabled,
  isBrainTravelEngineEnabled,
  isBrainTripPlanningEnabled,
  isBrainExecutionEnabled,
  isBrainSearchEnabled,
  isBrainRealProvidersEnabled,
  isBrainTripOrchestratorEnabled,
  isBrainContextMemoryEnabled,
  isUnifiedTravelPlannerEnabled,
  getOrCreateBrainOrchestrator,
  getOrCreateTripPlanningEngine,
  getOrCreateTravelExecutionEngine,
  seedBrainMemoryFromRequirements,
  brainMemoryToRequirementsPatch,
  toMetaBrain,
  withBrainMeta,
  runIntegratedBrainTurn,
  attachTravelExecution,
  attachSearchAggregation,
  runIntegratedBrainPipeline,
} from './integration'
export type {
  BrainMetaSnapshot,
  RunIntegratedBrainTurnInput,
} from './integration'

export {
  TripPlanningEngine,
  resetTripPlanningSessions,
  getPlanningSession,
  PlanningSessionApi,
  createPlanningSession,
  detectCorrections,
  applyCollectAndCorrections,
  detectMissingPlanningFields,
  nextPlanningFieldToAsk,
  buildClarificationPlan,
  buildTravelSummary,
  produceTripPlan,
  sessionToRequirements,
  PLANNING_INTAKE_ORDER,
  PLANNING_REQUIRED,
  isPlanningFieldFilled,
  planningCompleteness,
} from './tripPlanning'
export type {
  PlanningStage,
  PlanningField,
  PlanningSession,
  CorrectionKind,
  CorrectionPatch,
  ClarificationPlan,
  TravelSummary,
  TripPlanningTurnResult,
  TripPlanningEngineOptions,
  TripPlanningEngineHandle,
  /** Sprint 22 engine TripPlan (distinct from Sprint 21 brain TravelPlan). */
  TripPlan as EngineTripPlan,
} from './tripPlanning'

export {
  TravelExecutionEngine,
  resetTravelExecutionSessions,
  getLastTravelExecutionResult,
  ExecutionOrchestrator,
  buildExecutionTasksFromTripPlan,
  createExecutionPlan,
  createMockExecutionProviders,
  createExecutionProviders,
  resolveExecutionProviderConfig,
  clearAllProviderCaches,
  resetProviderMonitoring,
  createAmadeusFlightExecutionProvider,
  createBookingHotelExecutionProvider,
  withProviderResilience,
  getProviderMonitorSnapshot,
  getProviderCache,
  taskTypesInOrder,
} from './execution'
export type {
  ExecutionTaskType,
  ExecutionTaskStatus,
  ExecutionState,
  ExecutionTask,
  ExecutionPlan,
  ExecutionResult,
  ExecutionProgress,
  ExecutionSummary,
  TravelExecutionTurnResult,
  TravelExecutionEngineOptions,
  TravelExecutionEngineHandle,
  ExecutionProviderBundle,
  FlightProvider,
  HotelProvider,
  TransportProvider,
  ActivitiesProvider,
  ActivityProvider,
  PackageProvider,
  FlightSearchPayload,
  HotelSearchPayload,
  TransportSearchPayload,
  ActivitiesSearchPayload,
  PackageSearchPayload,
  ExecutionProviderRuntimeConfig,
  ExecutionProviderMode,
  CreateExecutionProvidersOptions,
  CreateExecutionProvidersResult,
} from './execution'

export {
  SearchAggregationEngine,
  aggregateSearch,
  aggregateFromExecution,
  normalizeExecutionResults,
  deduplicateOptions,
  rankAndScoreOptions,
  buildSearchRecommendation,
} from './search'
export type {
  SearchOptionKind,
  FlightOption,
  HotelOption,
  TransportOption,
  ActivityOption,
  PackageOption,
  SearchOption,
  SearchResult,
  SearchCollection,
  RankingFactorScores,
  RecommendationCandidate,
  SearchRecommendation,
  AggregationTimelineEntry,
  SearchAggregationTurnResult,
  SearchAggregationContext,
  SearchAggregationEngineOptions,
  SearchAggregationEngineHandle,
  RankingContext,
} from './search'

export {
  AITripOrchestrator,
  getOrCreateAITripOrchestrator,
  resetAITripOrchestrator,
  clearOrchestratorCache,
  resetOrchestratorMetrics,
  extractTravelIntentFromConversation,
  domainsForIntent,
  buildOrchestratorExecutionPlan,
  resolveOrchestratorDomains,
  createOrchestratorLogger,
  createOrchestratorMetricsCollector,
  getRecentOrchestratorMetrics,
  recordOrchestratorMetrics,
  buildOrchestratorCacheKey,
  getOrchestratorCached,
  setOrchestratorCached,
  orchestratorCacheSize,
} from './orchestrator'
export type {
  OrchestratorDomain,
  OrchestratorStage,
  OrchestratorLogLevel,
  OrchestratorLogEntry,
  OrchestratorDomainStep,
  OrchestratorExecutionPlan,
  OrchestratorMetrics,
  OrchestratorAggregatedResponse,
  AITripOrchestratorTurnResult,
  AITripOrchestratorOptions,
  AITripOrchestratorRunInput,
  AITripOrchestratorHandle,
} from './orchestrator'

export {
  MemoryExtractor,
  ConversationMemoryService,
  getConversationMemoryService,
  resetConversationMemoryService,
  UserPreferenceStore,
  emptyTravelPreferenceProfile,
  getUserPreferenceStore,
  resetUserPreferenceStore,
  ConversationSummarizer,
  ContextAssembler,
  mergeLongTermIntoSession,
  detectMissingPreferenceSlots,
  buildFollowUpQuestions,
  promptForExtendedSlot,
  MemoryContextEngine,
  getOrCreateMemoryContextEngine,
  resetMemoryContextEngine,
  createEmptyEnrichedMemory,
  enrichMemory,
  applyEnrichedPatch,
  ensureEnriched,
  sanitizeMemoryForPublic,
  sanitizeProfileForPublic,
  DEFAULT_MEMORY_EXPIRATION_POLICY,
  isBrainContextMemoryEnabled as isBrainContextMemoryFlagEnabled,
} from './memory'
export type {
  ExtendedMemorySlot,
  SeatPreference,
  MealPreference,
  VisaStatus,
  FamilyMember,
  PassportNationalitySlot,
  LoyaltyProgramEntry,
  ConversationMemoryExtensions,
  EnrichedConversationMemory,
  TravelPreferenceProfile,
  ShortTermMemoryState,
  ConversationSummary,
  AssembledContext,
  MemoryExtractionResult,
  MemoryEngineTurnResult,
  MemoryExpirationPolicy,
  ConversationMemoryServiceHandle,
  UserPreferenceStoreHandle,
  MemoryContextEngineHandle,
  MemoryContextEngineOptions,
} from './memory'

export {
  UnifiedTravelPlanner,
  getOrCreateUnifiedTravelPlanner,
  resetUnifiedTravelPlanner,
  emptyUnifiedContext,
  extractContextFromUserText,
  mergeUnifiedContext,
  contextFromMemoryLike,
  detectMissingUnifiedFields,
  buildUnifiedFollowUps,
  estimateTripCost,
  buildUnifiedItinerary,
  pairFlightsAndHotels,
  scoreAndRankPlans,
  searchUnifiedFlights,
  searchUnifiedHotels,
} from './unifiedTravel'
export type {
  UnifiedTravelPlannerStage,
  UnifiedPlanOptimizationFactor,
  UnifiedTripCostEstimate,
  UnifiedItineraryDay,
  UnifiedFlightLeg,
  UnifiedHotelStay,
  UnifiedTravelPlanOption,
  UnifiedFollowUpQuestion,
  UnifiedTravelPlanResult,
  UnifiedTravelPlannerContext,
  UnifiedTravelPlannerOptions,
  UnifiedTravelPlannerRunInput,
  UnifiedTravelPlannerHandle,
  UnifiedPlanCandidate,
} from './unifiedTravel'
