export {
  validateOwnership,
  sanitizeInput,
  validateDestination,
  validateSessionData,
  checkRateLimit,
  clearRateLimit,
  type OwnershipCheckResult,
} from './securityUtils'

/** Sprint 14 — Production Secret Management */
export {
  SECURITY_SECRET_MANAGER_VERSION,
  SECURITY_SECRET_MANAGER_FEATURE_ID,
  isSecretManagerEnabled,
  SecretManager,
  createSecretManager,
  getSecretManager,
  setSecretManagerForTests,
  resetSecretManagerForTests,
  EnvironmentSecretProvider,
  createEnvironmentSecretProvider,
  FutureVaultSecretProvider,
  createFutureVaultSecretProvider,
  FUTURE_VAULT_CAPABILITIES,
  MemorySecretProvider,
  createMemorySecretProvider,
  resolveProviderCredentials,
  readSecretViaManager,
  hasProviderCredentials,
  redactSecret,
  assertNoSecretLeak,
  listSecretAccessEvents,
  resetSecretAccessAuditForTests,
  PROVIDER_SECRET_REGISTRY,
  type SecretProvider,
  type SecretProviderId,
  type ProviderCredentialSet,
  type SecretAccessEvent,
  type SecretManagerDiagnostics,
} from './secrets'
