export {
  validateOwnership,
  sanitizeInput,
  validateDestination,
  validateSessionData,
  checkRateLimit,
  clearRateLimit,
  type OwnershipCheckResult,
} from './securityUtils'

/** Sprint 14 — Production Secret Management */
export {
  SECURITY_SECRET_MANAGER_VERSION,
  SECURITY_SECRET_MANAGER_FEATURE_ID,
  REDACTED_PLACEHOLDER,
  isSecretManagerEnabled,
  SecretManager,
  createSecretManager,
  getSecretManager,
  setSecretManagerForTests,
  resetSecretManagerForTests,
  EnvironmentSecretProvider,
  createEnvironmentSecretProvider,
  FutureVaultSecretProvider,
  createFutureVaultSecretProvider,
  FUTURE_VAULT_CAPABILITIES,
  MemorySecretProvider,
  createMemorySecretProvider,
  SecretRegistry,
  getSecretRegistry,
  resetSecretRegistryForTests,
  ValidationService,
  createValidationService,
  SecretSanitizer,
  createSecretSanitizer,
  sanitizeForLogs,
  resolveProviderCredentials,
  readSecretViaManager,
  hasProviderCredentials,
  readManagedEnv,
  readManagedConfig,
  readManagedSecret,
  redactSecret,
  assertNoSecretLeak,
  listSecretAccessEvents,
  resetSecretAccessAuditForTests,
  validateSecretsAtStartup,
  shouldDisableProvider,
  findServerSecretLeaksInBundle,
  listServerOnlySecretKeys,
  getSecretMetrics,
  resetSecretMetricsForTests,
  getSecretRotationController,
  resetSecretRotationForTests,
  createProviderSecretAuthorizer,
  PROVIDER_SECRET_REGISTRY,
  type SecretProvider,
  type SecretProviderId,
  type ProviderCredentialSet,
  type SecretAccessEvent,
  type SecretManagerDiagnostics,
  type SecretValidationReport,
  type SecretMetricsSnapshot,
} from './secrets'
