/**
 * Evolution Sprint 7 — DestinationKnowledge
 * Offline curated consultant knowledge — no external APIs.
 */

import type { CrowdLevel, DestinationKnowledgeRecord } from './destinationTypes'

function crowds(...levels: CrowdLevel[]): CrowdLevel[] {
  if (levels.length !== 12) throw new Error('crowdByMonth must have 12 entries')
  return levels
}

function climate(...labels: string[]): string[] {
  if (labels.length !== 12) throw new Error('climateByMonth must have 12 entries')
  return labels
}

/**
 * Compact but consultant-oriented destination knowledge.
 * Scores are 0–100 qualitative priors for matching — not live ratings.
 */
export const DESTINATION_KNOWLEDGE: DestinationKnowledgeRecord[] = [
  {
    id: 'japan',
    nameEn: 'Japan',
    nameAr: 'اليابان',
    aliases: ['tokyo', 'osaka', 'kyoto', 'طوكيو', 'يابان', 'اليابان'],
    region: 'East Asia',
    bestSeasons: [3, 4, 5, 10, 11],
    worstSeasons: [6, 7, 8],
    weatherPatterns: ['humid_summers', 'mild_springs', 'autumn_colors', 'cold_north_winters'],
    crowdByMonth: crowds('moderate', 'moderate', 'high', 'peak', 'high', 'moderate', 'high', 'high', 'moderate', 'high', 'peak', 'moderate'),
    typicalTravelerProfiles: ['culture', 'foodie', 'photography', 'city', 'family_older_kids'],
    familySuitability: 78,
    luxuryScore: 85,
    adventureScore: 55,
    foodScore: 95,
    shoppingScore: 88,
    walkingScore: 90,
    transportationQuality: 98,
    safetyIndicators: ['very_low_violent_crime', 'excellent_emergency_services'],
    safetyBand: 'high',
    costExpectations: 'premium',
    dailyBudgetSar: { low: 700, mid: 1200, high: 2200 },
    recommendedStayDays: { min: 7, ideal: 10, max: 14 },
    topStrengths: ['world-class transit', 'food culture', 'safety', 'seasonal beauty'],
    knownWeaknesses: ['language barrier outside hubs', 'summer humidity', 'peak cherry-blossom crowds'],
    climateByMonth: climate('cold', 'cold', 'cool', 'mild', 'mild', 'warm', 'hot', 'hot', 'warm', 'mild', 'cool', 'cold'),
    nightlifeScore: 70,
    photographyScore: 92,
    natureScore: 75,
    cityScore: 95,
    accessibilityScore: 88,
    localEventsNotes: ['cherry_blossom', 'autumn_foliage', 'new_year_travel_rush'],
    visaComplexity: 'moderate',
    visaNotes: ['Check current visa waiver / eVisa rules for Saudi travelers.'],
    evidence: ['curated_consultant_prior:japan_v1'],
    missingKnowledge: ['live_event_calendar', 'real_time_crowd_sensors'],
    confidence: 0.82,
  },
  {
    id: 'korea',
    nameEn: 'South Korea',
    nameAr: 'كوريا الجنوبية',
    aliases: ['seoul', 'busan', 'korea', 'سيول', 'كوريا'],
    region: 'East Asia',
    bestSeasons: [4, 5, 9, 10],
    worstSeasons: [7, 8],
    weatherPatterns: ['four_seasons', 'humid_summers', 'crisp_autumns'],
    crowdByMonth: crowds('moderate', 'moderate', 'moderate', 'high', 'high', 'moderate', 'high', 'high', 'high', 'peak', 'moderate', 'moderate'),
    typicalTravelerProfiles: ['city', 'foodie', 'shopping', 'nightlife', 'culture'],
    familySuitability: 72,
    luxuryScore: 80,
    adventureScore: 50,
    foodScore: 90,
    shoppingScore: 92,
    walkingScore: 85,
    transportationQuality: 95,
    safetyIndicators: ['low_violent_crime', 'strong_urban_infrastructure'],
    safetyBand: 'high',
    costExpectations: 'moderate',
    dailyBudgetSar: { low: 550, mid: 900, high: 1600 },
    recommendedStayDays: { min: 5, ideal: 7, max: 12 },
    topStrengths: ['K-culture & food', 'shopping', 'efficient transit', 'nightlife'],
    knownWeaknesses: ['hot humid summers', 'air quality episodes', 'language outside Seoul'],
    climateByMonth: climate('cold', 'cold', 'cool', 'mild', 'mild', 'warm', 'hot', 'hot', 'warm', 'mild', 'cool', 'cold'),
    nightlifeScore: 88,
    photographyScore: 85,
    natureScore: 60,
    cityScore: 94,
    accessibilityScore: 82,
    localEventsNotes: ['cherry_blossom', 'autumn_festivals', 'year_end_shopping'],
    visaComplexity: 'easy',
    visaNotes: ['Often visa-free / easy entry for many GCC passports — verify current rules.'],
    evidence: ['curated_consultant_prior:korea_v1'],
    missingKnowledge: ['live_air_quality'],
    confidence: 0.8,
  },
  {
    id: 'paris',
    nameEn: 'Paris',
    nameAr: 'باريس',
    aliases: ['france', 'باريس', 'فرنسا'],
    region: 'Europe',
    bestSeasons: [4, 5, 6, 9, 10],
    worstSeasons: [1, 2, 8],
    weatherPatterns: ['mild_springs', 'warm_summers', 'cool_rainy_winters'],
    crowdByMonth: crowds('moderate', 'moderate', 'high', 'peak', 'peak', 'high', 'peak', 'peak', 'high', 'high', 'moderate', 'high'),
    typicalTravelerProfiles: ['culture', 'romantic', 'luxury', 'foodie', 'photography'],
    familySuitability: 70,
    luxuryScore: 95,
    adventureScore: 35,
    foodScore: 94,
    shoppingScore: 95,
    walkingScore: 88,
    transportationQuality: 90,
    safetyIndicators: ['pickpocketing_hotspots', 'generally_safe_central_areas'],
    safetyBand: 'moderate',
    costExpectations: 'luxury',
    dailyBudgetSar: { low: 900, mid: 1500, high: 2800 },
    recommendedStayDays: { min: 4, ideal: 6, max: 10 },
    topStrengths: ['culture & museums', 'cuisine', 'luxury shopping', 'iconic photography'],
    knownWeaknesses: ['August closures/crowds', 'pickpockets', 'high cost'],
    climateByMonth: climate('cold', 'cold', 'cool', 'mild', 'mild', 'warm', 'warm', 'warm', 'mild', 'mild', 'cool', 'cold'),
    nightlifeScore: 85,
    photographyScore: 96,
    natureScore: 40,
    cityScore: 98,
    accessibilityScore: 75,
    localEventsNotes: ['fashion_weeks', 'summer_tourism_peak', 'christmas_markets'],
    visaComplexity: 'complex',
    visaNotes: ['Schengen visa typically required for Saudi travelers.'],
    evidence: ['curated_consultant_prior:paris_v1'],
    missingKnowledge: ['strike_calendar'],
    confidence: 0.84,
  },
  {
    id: 'rome',
    nameEn: 'Rome',
    nameAr: 'روما',
    aliases: ['italy', 'روما', 'إيطاليا', 'italy'],
    region: 'Europe',
    bestSeasons: [4, 5, 9, 10],
    worstSeasons: [7, 8],
    weatherPatterns: ['hot_summers', 'mild_springs', 'pleasant_autumns'],
    crowdByMonth: crowds('moderate', 'moderate', 'high', 'peak', 'peak', 'high', 'peak', 'peak', 'high', 'high', 'moderate', 'moderate'),
    typicalTravelerProfiles: ['culture', 'foodie', 'history', 'family', 'photography'],
    familySuitability: 75,
    luxuryScore: 82,
    adventureScore: 40,
    foodScore: 93,
    shoppingScore: 78,
    walkingScore: 80,
    transportationQuality: 72,
    safetyIndicators: ['pickpocketing_tourist_sites', 'generally_safe_central'],
    safetyBand: 'moderate',
    costExpectations: 'premium',
    dailyBudgetSar: { low: 700, mid: 1100, high: 2000 },
    recommendedStayDays: { min: 3, ideal: 5, max: 8 },
    topStrengths: ['history & ruins', 'cuisine', 'walkable historic core'],
    knownWeaknesses: ['summer heat & crowds', 'uneven sidewalks', 'transit less polished than northern Europe'],
    climateByMonth: climate('cool', 'cool', 'mild', 'mild', 'warm', 'hot', 'hot', 'hot', 'warm', 'mild', 'cool', 'cool'),
    nightlifeScore: 72,
    photographyScore: 94,
    natureScore: 35,
    cityScore: 92,
    accessibilityScore: 60,
    localEventsNotes: ['easter_crowds', 'summer_heatwave_risk'],
    visaComplexity: 'complex',
    visaNotes: ['Schengen visa typically required for Saudi travelers.'],
    evidence: ['curated_consultant_prior:rome_v1'],
    missingKnowledge: ['museum_ticket_blackouts'],
    confidence: 0.83,
  },
  {
    id: 'bali',
    nameEn: 'Bali',
    nameAr: 'بالي',
    aliases: ['indonesia', 'بالي', 'اندونيسيا'],
    region: 'Southeast Asia',
    bestSeasons: [4, 5, 6, 7, 8, 9],
    worstSeasons: [1, 2, 12],
    weatherPatterns: ['dry_season_mid_year', 'wet_season_dec_mar', 'tropical_humidity'],
    crowdByMonth: crowds('moderate', 'moderate', 'moderate', 'high', 'high', 'peak', 'peak', 'peak', 'high', 'moderate', 'moderate', 'high'),
    typicalTravelerProfiles: ['honeymoon', 'wellness', 'nature', 'adventure', 'photography'],
    familySuitability: 68,
    luxuryScore: 88,
    adventureScore: 78,
    foodScore: 80,
    shoppingScore: 65,
    walkingScore: 55,
    transportationQuality: 55,
    safetyIndicators: ['tourist_scams', 'road_safety_variable', 'generally_welcoming'],
    safetyBand: 'moderate',
    costExpectations: 'moderate',
    dailyBudgetSar: { low: 400, mid: 800, high: 1800 },
    recommendedStayDays: { min: 5, ideal: 8, max: 14 },
    topStrengths: ['nature & beaches', 'wellness', 'luxury villas', 'photography'],
    knownWeaknesses: ['traffic', 'wet season', 'variable road safety', 'overtourism pockets'],
    climateByMonth: climate('rainy', 'rainy', 'warm', 'warm', 'warm', 'warm', 'warm', 'warm', 'warm', 'warm', 'rainy', 'rainy'),
    nightlifeScore: 70,
    photographyScore: 90,
    natureScore: 95,
    cityScore: 45,
    accessibilityScore: 50,
    localEventsNotes: ['nyepi_day_restrictions', 'dry_season_peak'],
    visaComplexity: 'easy',
    visaNotes: ['Often VOA / easy entry — verify current Indonesian rules.'],
    evidence: ['curated_consultant_prior:bali_v1'],
    missingKnowledge: ['volcano_alert_status'],
    confidence: 0.8,
  },
  {
    id: 'phuket',
    nameEn: 'Phuket',
    nameAr: 'بوكيت',
    aliases: ['thailand', 'بوكيت', 'تايلند', 'phuket'],
    region: 'Southeast Asia',
    bestSeasons: [11, 12, 1, 2, 3],
    worstSeasons: [5, 6, 7, 8, 9],
    weatherPatterns: ['dry_coolish_winter', 'wet_southwest_monsoon'],
    crowdByMonth: crowds('peak', 'peak', 'high', 'high', 'moderate', 'low', 'low', 'low', 'low', 'moderate', 'high', 'peak'),
    typicalTravelerProfiles: ['beach', 'family', 'nightlife', 'luxury', 'snorkel'],
    familySuitability: 80,
    luxuryScore: 82,
    adventureScore: 60,
    foodScore: 78,
    shoppingScore: 70,
    walkingScore: 50,
    transportationQuality: 60,
    safetyIndicators: ['tourist_areas_patrol', 'scooter_accident_risk', 'water_safety'],
    safetyBand: 'moderate',
    costExpectations: 'moderate',
    dailyBudgetSar: { low: 450, mid: 850, high: 1700 },
    recommendedStayDays: { min: 4, ideal: 7, max: 12 },
    topStrengths: ['beaches', 'family resorts', 'value luxury', 'easy flights from Gulf'],
    knownWeaknesses: ['monsoon months', 'scooter risks', 'party-area noise'],
    climateByMonth: climate('warm', 'warm', 'warm', 'warm', 'rainy', 'rainy', 'rainy', 'rainy', 'rainy', 'warm', 'warm', 'warm'),
    nightlifeScore: 85,
    photographyScore: 80,
    natureScore: 75,
    cityScore: 50,
    accessibilityScore: 55,
    localEventsNotes: ['vegetarian_festival', 'high_season_dec_feb'],
    visaComplexity: 'easy',
    visaNotes: ['Often visa-exempt / VOA for many travelers — verify current Thai rules.'],
    evidence: ['curated_consultant_prior:phuket_v1'],
    missingKnowledge: ['beach_closure_notices'],
    confidence: 0.78,
  },
  {
    id: 'morocco',
    nameEn: 'Morocco',
    nameAr: 'المغرب',
    aliases: ['marrakech', 'casablanca', 'fez', 'مراكش', 'المغرب'],
    region: 'North Africa',
    bestSeasons: [3, 4, 5, 9, 10, 11],
    worstSeasons: [7, 8],
    weatherPatterns: ['hot_interior_summers', 'mild_coast', 'cool_atlas_winters'],
    crowdByMonth: crowds('moderate', 'moderate', 'high', 'peak', 'high', 'moderate', 'high', 'high', 'high', 'peak', 'high', 'moderate'),
    typicalTravelerProfiles: ['culture', 'adventure', 'foodie', 'photography', 'family'],
    familySuitability: 70,
    luxuryScore: 80,
    adventureScore: 75,
    foodScore: 88,
    shoppingScore: 85,
    walkingScore: 70,
    transportationQuality: 60,
    safetyIndicators: ['medina_hassle', 'generally_hospitable', 'road_fatigue_on_long_drives'],
    safetyBand: 'moderate',
    costExpectations: 'moderate',
    dailyBudgetSar: { low: 350, mid: 700, high: 1500 },
    recommendedStayDays: { min: 6, ideal: 9, max: 14 },
    topStrengths: ['culture & souks', 'food', 'varied landscapes', 'value luxury riads'],
    knownWeaknesses: ['summer heat inland', 'tourist hassle in medinas', 'uneven long-distance transit'],
    climateByMonth: climate('cool', 'cool', 'mild', 'mild', 'warm', 'hot', 'hot', 'hot', 'warm', 'mild', 'cool', 'cool'),
    nightlifeScore: 55,
    photographyScore: 90,
    natureScore: 80,
    cityScore: 75,
    accessibilityScore: 55,
    localEventsNotes: ['ramadan_timing_varies', 'rose_festival_regions'],
    visaComplexity: 'easy',
    visaNotes: ['Often visa-free for Saudi travelers — verify current rules.'],
    evidence: ['curated_consultant_prior:morocco_v1'],
    missingKnowledge: ['regional_festival_dates'],
    confidence: 0.79,
  },
  {
    id: 'spain',
    nameEn: 'Spain',
    nameAr: 'إسبانيا',
    aliases: ['madrid', 'barcelona', 'seville', 'مدريد', 'برشلونة', 'إسبانيا'],
    region: 'Europe',
    bestSeasons: [4, 5, 6, 9, 10],
    worstSeasons: [7, 8],
    weatherPatterns: ['hot_southern_summers', 'mild_springs', 'varied_by_region'],
    crowdByMonth: crowds('moderate', 'moderate', 'high', 'peak', 'peak', 'high', 'peak', 'peak', 'high', 'high', 'moderate', 'high'),
    typicalTravelerProfiles: ['culture', 'foodie', 'family', 'nightlife', 'city'],
    familySuitability: 82,
    luxuryScore: 85,
    adventureScore: 55,
    foodScore: 92,
    shoppingScore: 85,
    walkingScore: 85,
    transportationQuality: 88,
    safetyIndicators: ['pickpocketing_tourist_hubs', 'generally_safe'],
    safetyBand: 'moderate',
    costExpectations: 'premium',
    dailyBudgetSar: { low: 650, mid: 1100, high: 2000 },
    recommendedStayDays: { min: 5, ideal: 8, max: 14 },
    topStrengths: ['food & lifestyle', 'family-friendly cities', 'transit', 'nightlife'],
    knownWeaknesses: ['August heat/crowds', 'pickpockets in hubs', 'Schengen process'],
    climateByMonth: climate('cool', 'cool', 'mild', 'mild', 'warm', 'hot', 'hot', 'hot', 'warm', 'mild', 'cool', 'cool'),
    nightlifeScore: 90,
    photographyScore: 88,
    natureScore: 65,
    cityScore: 92,
    accessibilityScore: 80,
    localEventsNotes: ['semana_santa', 'summer_festivals'],
    visaComplexity: 'complex',
    visaNotes: ['Schengen visa typically required for Saudi travelers.'],
    evidence: ['curated_consultant_prior:spain_v1'],
    missingKnowledge: ['regional_strike_notices'],
    confidence: 0.81,
  },
  {
    id: 'istanbul',
    nameEn: 'Istanbul',
    nameAr: 'إسطنبول',
    aliases: ['turkey', 'اسطنبول', 'إسطنبول', 'تركيا'],
    region: 'Europe/Asia',
    bestSeasons: [4, 5, 9, 10],
    worstSeasons: [7, 8],
    weatherPatterns: ['mild_springs', 'hot_summers', 'cool_rainy_winters'],
    crowdByMonth: crowds('moderate', 'moderate', 'high', 'peak', 'high', 'high', 'peak', 'peak', 'high', 'peak', 'moderate', 'high'),
    typicalTravelerProfiles: ['family', 'culture', 'foodie', 'shopping', 'city'],
    familySuitability: 85,
    luxuryScore: 80,
    adventureScore: 45,
    foodScore: 90,
    shoppingScore: 88,
    walkingScore: 75,
    transportationQuality: 80,
    safetyIndicators: ['busy_tourist_zones', 'generally_popular_with_gulf_families'],
    safetyBand: 'moderate',
    costExpectations: 'moderate',
    dailyBudgetSar: { low: 450, mid: 700, high: 1400 },
    recommendedStayDays: { min: 4, ideal: 6, max: 10 },
    topStrengths: ['culture', 'food', 'family fit', 'shopping', 'short flight from Gulf'],
    knownWeaknesses: ['summer crowds', 'traffic', 'tourist pricing pockets'],
    climateByMonth: climate('cold', 'cold', 'cool', 'mild', 'mild', 'warm', 'hot', 'hot', 'warm', 'mild', 'cool', 'cold'),
    nightlifeScore: 75,
    photographyScore: 88,
    natureScore: 50,
    cityScore: 95,
    accessibilityScore: 70,
    localEventsNotes: ['ramadan_iftar_culture', 'summer_tourism_peak'],
    visaComplexity: 'easy',
    visaNotes: ['Often eVisa / easy process for Saudi travelers — verify current rules.'],
    evidence: ['curated_consultant_prior:istanbul_v1'],
    missingKnowledge: ['live_hotel_events'],
    confidence: 0.85,
  },
  {
    id: 'dubai',
    nameEn: 'Dubai',
    nameAr: 'دبي',
    aliases: ['uae', 'دبي', 'الإمارات'],
    region: 'Gulf',
    bestSeasons: [11, 12, 1, 2, 3],
    worstSeasons: [6, 7, 8],
    weatherPatterns: ['hot_humid_summers', 'mild_pleasant_winters'],
    crowdByMonth: crowds('peak', 'peak', 'high', 'high', 'moderate', 'low', 'low', 'low', 'low', 'moderate', 'high', 'peak'),
    typicalTravelerProfiles: ['family', 'luxury', 'shopping', 'city', 'nightlife'],
    familySuitability: 92,
    luxuryScore: 98,
    adventureScore: 50,
    foodScore: 88,
    shoppingScore: 98,
    walkingScore: 45,
    transportationQuality: 90,
    safetyIndicators: ['very_low_violent_crime', 'strong_tourist_policing'],
    safetyBand: 'high',
    costExpectations: 'luxury',
    dailyBudgetSar: { low: 700, mid: 1400, high: 3000 },
    recommendedStayDays: { min: 3, ideal: 5, max: 8 },
    topStrengths: ['luxury', 'family attractions', 'shopping', 'safety', 'ease for GCC'],
    knownWeaknesses: ['extreme summer heat', 'outdoor walking limited in summer', 'high cost'],
    climateByMonth: climate('mild', 'mild', 'warm', 'hot', 'hot', 'hot', 'hot', 'hot', 'hot', 'warm', 'mild', 'mild'),
    nightlifeScore: 90,
    photographyScore: 85,
    natureScore: 35,
    cityScore: 96,
    accessibilityScore: 90,
    localEventsNotes: ['shopping_festivals', 'winter_peak_season'],
    visaComplexity: 'easy',
    visaNotes: ['GCC-friendly entry — verify current UAE rules.'],
    evidence: ['curated_consultant_prior:dubai_v1'],
    missingKnowledge: ['event_ticket_sellouts'],
    confidence: 0.88,
  },
]

export function findDestinationKnowledge(query: string): DestinationKnowledgeRecord | null {
  const q = query.trim().toLowerCase()
  if (!q) return null
  for (const d of DESTINATION_KNOWLEDGE) {
    if (d.id === q || d.nameEn.toLowerCase() === q || d.nameAr === query.trim()) return d
    if (d.aliases.some((a) => a.toLowerCase() === q || q.includes(a.toLowerCase()) || a.toLowerCase().includes(q))) {
      return d
    }
  }
  // Fuzzy contains
  for (const d of DESTINATION_KNOWLEDGE) {
    if (q.includes(d.nameEn.toLowerCase()) || d.nameEn.toLowerCase().includes(q)) return d
    if (query.includes(d.nameAr)) return d
  }
  return null
}

export function listDestinationKnowledge(): DestinationKnowledgeRecord[] {
  return [...DESTINATION_KNOWLEDGE]
}

export const DestinationKnowledge = {
  all: listDestinationKnowledge,
  find: findDestinationKnowledge,
  records: DESTINATION_KNOWLEDGE,
}
