/**
 * Phase 7 Stage 1 — Traveler Profile Foundation barrel.
 *
 * Architecture / contracts / types / blueprints only.
 * Gated by `brain.traveler_profile` (default OFF).
 * Distinct from UI `ui.traveler_profile`.
 * No DB, auth, storage, OCR, LLM, Runtime, HTTP, or APIs.
 */

import { TRAVELER_PROFILE_ISOLATION as TP_ISOLATION } from './types'
import { PROFILE_PREFERENCE_DOMAINS, PROFILE_SECTION_IDS } from './types'

export {
  BRAIN_TRAVELER_PROFILE_FEATURE_ID,
  isBrainTravelerProfileEnabled,
  listProfileRegistry,
  listProfileSectionIds,
  ProfileRegistry,
  PROFILE_REGISTRY,
} from './registry'

export type {
  ProfileLocale,
  ProfileStatusId,
  ProfileTimelineEventKind,
  ProfilePreferenceDomain,
  ProfileDocumentKind,
  ProfileSectionId,
  TravelerProfileContract,
  TravelerIdentityContract,
  TravelerPreferencesContract,
  TravelStyleContract,
  TravelInterestsContract,
  BudgetPreferencesContract,
  AccommodationPreferencesContract,
  TransportationPreferencesContract,
  FoodPreferencesContract,
  AccessibilityPreferencesContract,
  LanguagePreferencesContract,
  FavoriteDestinationsContract,
  FavoriteAirlinesContract,
  FavoriteHotelsContract,
  FavoriteActivitiesContract,
  FamilyProfileContract,
  CompanionProfileContract,
  PassportMetadataContract,
  VisaMetadataContract,
  TravelDocumentsRegistryEntry,
  TravelDocumentsRegistryContract,
  EmergencyContactsContract,
  NotificationPreferencesContract,
  PrivacySettingsContract,
  ConsentRegistryEntry,
  ConsentRegistryContract,
  ProfileTimelineEvent,
  ProfileTimelineContract,
  ProfileAuditEntry,
  ProfileAuditTrailContract,
  ProfileVersioningContract,
  ProfileStatusContract,
  ProfileValidationContract,
  ProfileEvidenceBuilderContract,
  TravelerMemoryContract,
  ContextEnrichmentContract,
  PreferenceLearningContract,
  TravelTasteAnalyzerContract,
  ProfileRegistryEntry,
  TravelerProfileBlueprint,
} from './types'

export {
  TRAVELER_PROFILE_ISOLATION,
  PROFILE_PREFERENCE_DOMAINS,
  PROFILE_STATUS_IDS,
  PROFILE_SECTION_IDS,
} from './types'

export {
  buildTravelerProfile,
  buildTravelerIdentity,
  buildTravelerPreferences,
  buildTravelStyle,
  buildTravelInterests,
  buildBudgetPreferences,
  buildAccommodationPreferences,
  buildTransportationPreferences,
  buildFoodPreferences,
  buildAccessibilityPreferences,
  buildLanguagePreferences,
  buildFavoriteDestinations,
  buildFavoriteAirlines,
  buildFavoriteHotels,
  buildFavoriteActivities,
  buildFamilyProfile,
  buildCompanionProfiles,
  buildPassportMetadata,
  buildVisaMetadata,
  buildTravelDocumentsRegistry,
  buildEmergencyContacts,
  buildNotificationPreferences,
  buildPrivacySettings,
  buildConsentRegistry,
  buildProfileTimeline,
  buildProfileAuditTrail,
  buildProfileVersioning,
  buildProfileStatus,
  buildProfileValidation,
  buildProfileEvidenceBuilder,
  buildTravelerMemoryContract,
  buildContextEnrichmentContract,
  buildPreferenceLearningContract,
  buildTravelTasteAnalyzerContract,
} from './pipelines'

export {
  TravelerProfileFoundation,
  buildTravelerProfileBlueprint,
  tryBuildTravelerProfileBlueprint,
  assertTravelerProfileIsolation,
} from './engine'
export type { BuildTravelerProfileBlueprintOptions } from './engine'

export const TRAVELER_PROFILE_ARCHITECTURE = {
  version: '7.1.0-traveler-profile',
  featureId: 'brain.traveler_profile' as const,
  architectureOnly: true,
  components: [
    'traveler_profile',
    'traveler_identity',
    'traveler_preferences',
    'travel_style',
    'travel_interests',
    'budget_preferences',
    'accommodation_preferences',
    'transportation_preferences',
    'food_preferences',
    'accessibility_preferences',
    'language_preferences',
    'favorite_destinations',
    'favorite_airlines',
    'favorite_hotels',
    'favorite_activities',
    'family_profile',
    'companion_profiles',
    'passport_metadata',
    'visa_metadata',
    'travel_documents_registry',
    'emergency_contacts',
    'notification_preferences',
    'privacy_settings',
    'consent_registry',
    'profile_timeline',
    'profile_audit_trail',
    'profile_versioning',
    'profile_status',
    'profile_validation',
    'profile_evidence_builder',
    'traveler_memory_contract',
    'context_enrichment_contract',
    'preference_learning_contract',
    'travel_taste_analyzer_contract',
  ] as const,
  preferenceDomains: PROFILE_PREFERENCE_DOMAINS,
  sectionIds: PROFILE_SECTION_IDS,
  ...TP_ISOLATION,
} as const
