/**
 * Phase AB–AH — AI enhancement through Frontend Trip Planner Integration v1.
 * Additive library surface; no UI; no breaking TripPlan / ProviderAdapter changes.
 */

export {
  type FeatureLifecycle,
  type FeatureId,
  type FeatureDefinition,
  type FeatureRegistrySnapshot,
  FeatureRegistry,
  getFeatureRegistry,
  resetFeatureRegistry,
  createDefaultFeatureRegistry,
} from './featureFlags'

export {
  type TravelStyle,
  type TravelerPreferences,
  type HotelPreferences,
  type AirlinePreferences,
  type BudgetProfile,
  type TravelStyleProfile,
  type PreferenceWeights,
  type PersonalizationProfile,
  type PreferenceEngine,
  type PreferenceEngineOptions,
  type ExplicitPreferences,
  type InferredPreferences,
  type NormalizedPreferences,
  defaultPreferenceWeights,
  emptyPersonalizationProfile,
  InMemoryPreferenceEngine,
  getPreferenceEngine,
  resetPreferenceEngine,
  normalizePreferenceWeights,
  calculatePreferenceWeights,
} from './preferences'

export {
  type RankableItem,
  type RankedItem,
  type RankingInput,
  type RankingEngine,
  DefaultRankingEngine,
  RankingEngineImpl,
  createRankingEngine,
  stableSort,
  breakTies,
} from './ranking'

export {
  type RecommendationCandidate,
  type RecommendationRequest,
  type RecommendationResult,
  type RecommendationEngineContract,
  type RecommendationKind,
  type RecommendationReasonCategory,
  type RecommendationReason,
  type RecommendationScoreComponents,
  type RecommendationScore,
  type SeasonName,
  type RecommendationContext,
  type RecommendationCandidateInput,
  type Recommendation,
  type RecommendV1Request,
  type RecommendV1Result,
  RecommendationEngine,
  DefaultRecommendationEngine,
  createRecommendationEngine,
  scoreCandidate,
  toRecommendationScore,
  seasonFromMonth,
  resolveSeason,
} from './recommendations'

export {
  type MultiDestinationPlanInput,
  type MultiDestinationSegment,
  type MultiDestinationOutline,
  type AlternativeItineraryVariant,
  type ExplainableRecommendation,
  type PlanningConfidence,
  buildMultiDestinationOutline,
  generateAlternativeItineraries,
  scorePlanningConfidence,
  buildExplainableRecommendation,
  applyPreferenceWeighting,
  estimatePreferenceFit,
} from './planning'

export {
  type AnalyticsEventName,
  type AnalyticsEvent,
  type FunnelMetrics,
  type AnalyticsSnapshot,
  type AnalyticsRecorderOptions,
  type ProductAnalytics,
  InMemoryProductAnalytics,
  getProductAnalytics,
  resetProductAnalytics,
} from './analytics'

export {
  type ItineraryOptimizationGoal,
  type ActivitySlotKind,
  type ActivitySlot,
  type ItineraryDay as AiItineraryDay,
  type CostBreakdown,
  type OptimizationScores,
  type OptimizationResult,
  type ItineraryFlightLeg,
  type ItineraryHotelStay,
  type ItineraryTransportLeg,
  type ItineraryExplanation,
  type Itinerary as GeneratedItinerary,
  type ItineraryEngineInput,
  ItineraryEngine,
  createItineraryEngine,
  scoreTravelTime,
  scoreBudgetFit,
  scorePreferenceFit,
  scoreActivityDiversity,
  computeOptimizationScores,
  optimizeDayForTravelTime,
  optimizeDaysForBudget,
  optimizeDaysForPreferences,
  optimizeDaysForDiversity,
  buildOptimizationResult,
} from './itinerary'

export {
  type Booking,
  type BookingItem,
  type BookingItemKind,
  type BookingItemStatus,
  type BookingItineraryInput,
  type BookingPipelineOptions,
  type BookingState,
  type BookingSummary,
  type BookingTimeline,
  type BookingTimelineEvent,
  type CreateBookingInput,
  type RetryPolicy,
  type RetryAttemptResult,
  type SimulatedPaymentRequest,
  type SimulatedPaymentResult,
  type BookingOrchestratorOptions,
  BOOKING_STATE_TRANSITIONS,
  canTransitionBookingState,
  BookingIdempotencyStore,
  DEFAULT_BOOKING_RETRY_POLICY,
  withBookingRetry,
  simulatePayment,
  BookingOrchestrator,
  createBookingOrchestrator,
  resetBookingOrchestratorCounters,
} from './booking'

export {
  type BookingPreview,
  type PipelineConfidence,
  type PipelineNormalizedPreferences,
  type PreferenceSourceRecord,
  type PreferredLanguage,
  type TripPlannerRequest,
  type TripPlannerResult,
  type TripPlannerStage,
  type TripPlannerStatus,
  type TripPlannerValidationError,
  type TripPlannerFailure,
  type TripPlannerPipelineEvent,
  type TripPlannerTimeouts,
  type TripPlannerServiceOptions,
  type TripPlannerFailStage,
  type TripPlannerMetrics,
  type PipelineExecutionState,
  DEFAULT_TRIP_PLANNER_TIMEOUTS,
  SUPPORTED_TRIP_CURRENCIES,
  validateTripPlannerRequest,
  resolveCurrency,
  resolveDurationDays,
  buildRecommendationCandidates,
  calculatePipelineConfidence,
  InMemoryTripPlannerExecutionRepository,
  InMemoryTripPlannerEventRepository,
  InMemoryTripPlannerResultRepository,
  InMemoryTripPlannerMetrics,
  getTripPlannerMetrics,
  resetTripPlannerMetrics,
  TripPlannerService,
  createTripPlannerService,
  resetTripPlannerCounters,
  resetTripPlannerTestSingletons,
} from './tripPlanner'

export {
  type TripPlannerApiAction,
  type TripPlannerApiErrorBody,
  type TripPlannerAuthUser,
  type TripPlannerAuthResolver,
  type TripPlannerHttpHandlerOptions,
  type CreateTripPlanRequestDto,
  type CreateTripPlanResponseDto,
  type TripPlanResultDto,
  type TripPlanStatusDto,
  type TripPlanTimelineDto,
  type TripPlanErrorDto,
  extractBearerToken,
  createDevTokenAuthResolver,
  createSupabaseJwtAuthResolver,
  assertUserOwnsRequest,
  handleTripPlannerHttpRequest,
  createTripPlannerHttpHandler,
  progressForStage,
  progressFromTimeline,
  TripPlannerPlanStore,
  getTripPlannerApiMetrics,
  resetTripPlannerApiMetrics,
  handleTripPlannerRestRequest,
} from './tripPlanner'

export {
  mapTravelSessionToTripPlannerRequest,
  adaptTripPlannerResultToSearchOrchestration,
  adaptReasoningMap,
  localizeValidationErrors,
  formatApiTransportError,
  runTripPlannerFlow,
  STAGE_LABELS_AR,
  STAGE_LABELS_EN,
} from './tripPlanner'
