/**
 * Phase AB — product FeatureRegistry (distinct from Phase W provider flags).
 */

export type FeatureLifecycle = 'experimental' | 'beta' | 'stable' | 'deprecated'

export type FeatureId =
  | 'ai.multi_destination'
  | 'ai.alternative_itineraries'
  | 'ai.confidence_scoring'
  | 'ai.explainable_recommendations'
  | 'ai.preference_weighting'
  | 'ai.personalization'
  | 'ai.recommendation_engine'
  | 'ai.analytics'
  | 'ai.concierge'
  | 'ai.travel_reasoning'
  | 'ai.consultant_reasoning'
  | 'ai.consultant_reflection'
  | 'ai.planning_graph'
  | 'ai.traveler_intelligence'
  | 'ai.smart_clarification'
  | 'ai.persistent_memory'
  | 'ai.rahhal_brain'
  | 'ai.brain.v1'
  | 'ai.brain.v1.preview'
  | 'ai.autonomous_agent'
  | 'ai.booking_intelligence'
  | 'ai.budget_intelligence'
  | 'ai.conversation_intelligence'
  | 'ai.traveler_personalization'
  | 'ai.trip_optimizer'
  | 'ai.travel_planner'
  | 'ai.autonomous_decision'
  | 'ai.adaptive_learning'
  | 'ai.price_intelligence'
  | 'ai.dynamic_packages'
  | 'ai.itinerary_refinement'
  | 'ai.unified_trip'
  | 'ai.constitution'
  | 'ai.alpha_experience'
  | 'ai.concierge_experience'
  | 'ai.booking_assistant'
  | 'ai.booking_execution_confirmation'
  | 'ai.live_provider_gateway'
  | 'ai.live_flight_search'
  | 'ai.response_composer'
  | 'ai.live_hotel_search'
  | 'ai.conversational_provider_unify'
  | 'ai.live_flight_provider_pilot'
  | 'ai.integration_trip_orchestrator'
  | 'ai.integration_destination_intelligence'
  | 'ai.integration_trip_companion'
  | 'ai.integration_maps_mobility'
  | 'ai.integration_budget_pricing'
  | 'ai.integration_disruption_recovery'
  | 'ai.integration_action_execution'
  | 'ai.integration_journey'
  | 'security.secret_manager'
  | 'observability.platform'
  | 'load_testing.platform'
  | 'production_audit.platform'
  | 'rc1.validation'
  | 'soak.staging'
  | 'rc2.ga_review'
  | 'ai.trip_builder'
  | 'ai.memory_engine'
  | 'ai.orchestrator'
  | 'ai.itinerary_engine'
  | 'ai.execution_pipeline'
  | 'ai.streaming_conversation'
  | 'ai.editable_conversation'
  | 'ai.live_conversation'
  | 'ai.my_trips_dashboard'
  | 'booking.orchestrator'
  | 'ai.live_providers'
  | 'provider.amadeus'
  | 'providers.amadeus.enabled'
  | 'provider.duffel'
  | 'provider.booking'
  | 'ai.booking_execution'
  | 'ai.trip_management'
  | 'ai.document_center_v2'
  | 'ai.transaction_manager'
  | 'ai.booking_resume'
  | 'ai.payments'
  | 'ai.ticketing'
  | 'ai.refunds'
  | 'ai.travel_executive'
  | 'ai.executive_platform'
  | 'ai.executive_os'
  | 'ai.real_world_intelligence'
  | 'ui.flight_results_experience'
  | 'ui.passenger_booking_flow'
  | 'ui.my_trips'
  | 'ui.booking_history'
  | 'ui.booking_confirmation'
  | 'ui.supplier_adapter'
  | 'ui.booking_timeline'
  | 'ui.booking_flow'
  | 'ui.order_management'
  | 'ui.checkout_review'
  | 'ui.payment_preparation'
  | 'ui.ai_home'
  | 'ui.conversation_home'
  | 'ui.travel_cards'
  | 'ui.continue_booking'
  | 'ui.smart_itinerary'
  | 'ui.travel_insights'
  | 'ui.daily_planner'
  | 'brain.enabled'
  | 'brain.memory'
  | 'brain.intent'
  | 'brain.planner'
  | 'brain.debug'
  | 'brain.concierge'
  | 'brain.agent_handoff'
  | 'brain.voice'
  | 'brain.travel_engine'
  | 'brain.trip_planning'
  | 'brain.execution'
  | 'brain.search'
  | 'brain.real_providers'
  | 'brain.trip_orchestrator'
  | 'brain.context_memory'
  | 'brain.unified_travel_planner'
  | 'brain.conversation_ui'
  | 'brain.travel_execution_engine'
  | 'brain.payments_platform'
  | 'brain.trip_management'
  | 'brain.refund_policy_engine'
  | 'brain.travel_disruption_engine'
  | 'brain.loyalty_platform'
  | 'brain.travel_documents'
  | 'brain.supplier_marketplace'
  | 'brain.finance_platform'
  | 'ui.conversation_experience'
  | 'brain.ai_orchestrator'
  | 'ui.chatgpt_experience'
  | 'ui.experience_v1'
  | 'ui.production_integration'
  | 'ui.premium_home'
  | 'ui.new_experience'
  | 'providers.hotel_foundation'
  | 'payments.live'
  | 'providers.live_master'

export interface FeatureDefinition {
  id: FeatureId
  name: string
  description: string
  lifecycle: FeatureLifecycle
  /** When false, feature is registered but inactive. */
  enabled: boolean
  /** Optional dependency feature IDs that must also be enabled. */
  dependsOn?: FeatureId[]
  /** Notes for deprecation / migration. */
  notes?: string
}

export interface FeatureRegistrySnapshot {
  features: FeatureDefinition[]
  enabledIds: FeatureId[]
}
